version: '3.8'

services:
  mysql-consumer:
    image: mysql:8.0
    container_name: mysql-consumer
    restart: always
    environment:
      MYSQL_DATABASE: weather_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql-consumer-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-consumer
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql-consumer-data:

